### ISSUE TITLE
Another folder

### ISSUE THREAD

**Issue by krasnovpro** [myshov/libxkbswitch-macosx#1]
Can I put libxkbswitch.dylib into another folder, not in /usr/local/lib? And point this path in vimrc.

**Comment by myshov** [comment]
@quaritexa Hi!
Of course you can. As said in the README of [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) plugin you can put library anywhere you want and put in your vimrc this line:

``` viml
let g:XkbSwitchLib = '/usr/other/dir/libxkbswitch.dylib'
```

**Comment by krasnovpro** [comment]
This `let g:XkbSwitchLib = $HOME.'/.vim/bin/libxkbswitch.dylib'` not works.

**Comment by myshov** [comment]
Your code should work. Check that dylib file in appropriate directory, and there is no any errors in your vimrc file.

**Comment by krasnovpro** [comment]
I checked before I wrote first message. It doesn't work at all.

**Comment by myshov** [comment]
Let's explore your issue:
1. Which version of OS and Vim do you use?
2. Did you install [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) plugin itself properly?
3. Does library work if you put it in the directory from $PATH variable (for example `/usr/local/lib`)?

**Comment by krasnovpro** [comment]
1. OS X 10.10.5, MacVim 8.0 (110).
2. Plug 'lyokha/vim-xkbswitch'
3. Library only works if it lays in /usr/local/lib and xkbswitch in /usr/local/bin.
   Any other folders don't affect, even if they are included into the path variable.

**Comment by krasnovpro** [comment]
Problem solved. This tool works from any folder: https://github.com/vovkasm/input-source-switcher
